# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janelas\janela_inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: white;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("janelas\\../../InaflexAPP/static/apple-touch-icon.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(-10, -10, 411, 61))
        self.label_5.setStyleSheet("background: black;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.labelBD = QtWidgets.QLabel(Form)
        self.labelBD.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.labelBD.setObjectName("labelBD")
        self.label_5.raise_()
        self.label_7.raise_()
        self.label_6.raise_()
        self.labelBD.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "BACKGROUND APP"))
        self.labelBD.setText(_translate("Form", "TextLabel"))
